### ISSUE TITLE
Non privileged User windows Installation 

### ISSUE THREAD

**Issue by athuld** [Wraient/curd#19]
Is it possible to provide a non privileged user installation method. The current installer requires admin privileges and considering this as a script it shouldn't require admin privileges to function.

**Comment by Wraient** [comment]
admin privileges are required at 2 parts in this script

1. Installing script - We need to move the script at /usr/bin which is a root folder therefore moving anything there requires admin privileges
2. Updating script - It is the same because while updating the script there needs to be admin privileges to replace the binary at /usr/bin

If you do not want to give it any privileges, its possible to just download the binary and add it to your path, then you do not need any privileges.

If you have any other queries i'd be happy to answer

**Comment by athuld** [comment]
Can't we install the script to the local bin path. Usually scoop and other applications have a non privileged user installation which has a similar approach I was wondering the if that could be done.

As for your suggestion you have mentioned. I have tried with the binary file but my mpv installation is done as a non privileged user through scoop and it's throwing an mpv process error.

PS: all these non privileged shenanigans is to set this up in my work pc since my personal laptop is an old potato which doesn't have a proper display. So going through a lot of hoops to set this up. Have tried other scripts but the anilist sync is a must for me. So please don't mind me pestering you with all this issue. Apologies in advance 😅

**Comment by Wraient** [comment]
Are you using windows?
I would be happy to help you setup curd in your pc, if you are okay with it, we can figure out a solution on discord which would be faster.

**Comment by athuld** [comment]
Sure  I have messaged in the discord chat. We'll continue there. So closing the issue
